use_frameworks!

platform :ios, '8.0'


target "DisneyPhotoAuto" do
 
  pod 'AFNetworking', '~> 3.0'
  pod 'SDWebImage', '~>3.7'
  pod 'LBXScan', '~> 2.0'
  pod 'Masonry', '~> 1.0.2'
  pod 'ESPictureBrowser'
  pod 'MBProgressHUD'
  pod 'BmobSDK'
end
